-- IPEA 
-- SERCODIGO;VALDATA;VALVALOR;NIVNOME;TERCODIGO
CREATE TABLE EDA.IPEA
(
    SERCODIGO VARCHAR(20),
    VALDATA TIMESTAMP,
    VALVALOR NUMERIC,
    NIVNOME VARCHAR(100),
    TERCODIGO VARCHAR(30),
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL DEFAULT current_timestamp
);